export const URL_IO = 'http://localhost:3000'
export const URL_API = 'http://localhost:3000/api/'
export const URL_API_SHORT = '/api/'
export const URL_DASHBOARD = 'panel'
export const PROJECT_NAME = 'project-name'
export const PROJECT_URL = 'project/'
export const PROJECTS_URL = 'projects'
export const TAGS_URL = 'tags'
export const USERS_URL = 'users'
export const ADMINS_URL = 'admins'
export const PHOTO_URL = 'photo'
export const USERS_GET_BY_ID_URL = 'getById'
export const COOKIES_USER_URL = 'cookies/user'
export const SESSION_USER_URL = 'session/user'
export const ACHIEVEMENTS = 'achievements'
export const PETS_URL = 'pets'
export const TUTORIAL_URL = 'tutorial'
export const URL_COLLECTION_TASK = 'tasks'
export const URL_COMMENTS = 'comments'
export const URL_NEW_PROJECT = 'nuevo-proyecto'
export const URL_ALL_TASKS = 'lista-tareas'
export const URL_PROFILE = 'perfil'
export const ACTIVITY_URL = 'activity'
export const TASKS_COMPLETED = 'tasks-completed'
export const ARRAY_TASKS_STATES = ['pendiente', 'proceso', 'completada']
export const ARRAY_TASKS_PRIORITY = ['alta', 'media', 'baja']
export const ARRAY_PROJECT_STATE = ['En curso', 'Pausado', 'Cancelado', 'Finalizado']
export const TUTORIAL = { stepsFirstScreen: 'stepsFirstScreen', stepsCreateNewTask: 'stepsCreateNewTask', stepsProfile: 'stepsProfile' }
export const OBJECT_PROJECT = [{ id: 1, name: 'Veterinaria', color: '#EF518D', to: 'veterinaria' }, { id: 2, name: 'Manicurista', color: '#7AD8C7', to: 'manicurista' }, { id: 3, name: 'Tesis Da Vinci', color: '#685FD3', to: 'tesis-da-vinci' }, { id: 4, name: 'Tienda', color: '#EB996E', to: 'tienda' }]
export const OBJECT_TASKS_STATES_TEXT = { pendiente: 'Pendientes', proceso: 'En curso', completada: 'Terminadas' }
export const PRIORITY_ORDER = { baja: 1, media: 2, alta: 3 }
export const ORDER_BY = ['default', 'priorityDesc', 'dateAsc']
export const OBJECT_TAGS = [{ id: 1, name: 'Diseño', color: '#EF518D' }, { id: 2, name: 'Programación', color: '#F6A67C' }, { id: 3, name: 'Marketing', color: '#685FD3' }, { id: 4, name: 'Promoción', color: '#7AD8C7' }]
export const ORDER_BY_TEXT = { default: 'Predeterminado', priorityDesc: 'Prioridad', dateAsc: 'Fecha de entrega' }
export const COLOR_PRIMARY = '#DF437E'
export const COLOR_TEXT = '#020100'
export const COLOR_SVG_NAV = '#1C1C1C'
export const COLOR_SVG_NAV_ACTIVE = '#FFFFFF'
export const COLOR_PROJECT_CARD = ['#EF518D', '#F6A67C', '#7AD8C7']
export const PROJECT_SECTIONS_NAMES = ['Tablero', 'Agenda', 'Analíticas', 'Ranking']
export const PROFILE_PICTURES_DEFAULT = ['default-profile-bear', 'default-profile-bird', 'default-profile-cat', 'default-profile-cow', 'default-profile-dino', 'default-profile-giraffe', 'default-profile-lion', 'default-profile-panda', 'default-profile-penguin', 'default-profile-rabbit', 'default-profile-tiger']
export const PROJECT_SECTIONS_LINKS = [{ id: 1, name: 'Tablero', to: 'tablero', component: 'DiarySection' }, { id: 2, name: 'Agenda', to: 'agenda', component: 'DiarySection' }, { id: 3, name: 'Analíticas', to: 'analiticas', component: 'AnalyticsSection' }, { id: 4, name: 'Actividad', to: 'actividad', component: 'ActivitySection' }]
export const PATH_LINKS = { dashboard: '/panel', notifications: '/notificaciones', allTasks: '/lista-tareas', project: '/project', signup: '/registrarse', login: '/iniciar-sesion', profile: '/perfil', newProject: '/nuevo-proyecto', allAchievements: '/mis-insignias', waitingList: '/solicitudes', user: '/usuario', tasks: '/tareas' }
export const IMG_LINKS = { dashboard: 'dashboard-icon', notifications: 'notification-icon', allTasks: 'tasks-list-icon' }
export const COLORS_ARRAY = ['#DF437E', '#020100', '#71CEBD', '#B5DC7E', '#EF518D', '#F6A67C', '#7AD8C7']
export const ACTIVITY_TYPE_MSG = { moveTask: 'moveTask', addTask: 'addTask', editTask: 'editTask', deleteTask: 'deleteTask', dupTask: 'dupTask', editTaskDate: 'editTaskDate', recovered: 'recovered', addAchievement: 'addAchievement', commentAdded: 'commentAdded' }
export const ERRORS_MSG = { email: 'El email ingresado no es válido', existingEmail: 'El email ingresado ya existe', password: 'La contraseña ingresada no es válida', confirmPassword: 'Verificá que la contraseña sea la misma en ambos campos', login: 'El email o la contraseña ingresados no son válidos' }
export const ALERT_TYPE = { success: 'success', error: 'error' }
export const ALERT_MSG = { taskAdded: 'La tarea se creó correctamente', taskDeleted: 'La tarea se eliminó correctamente', taskEdited: 'La tarea se editó correctamente', taskDuplicated: 'La tarea se duplicó correctamente', taskMoved: 'La tarea se movió correctamente', taskDateEdited: 'La fecha de la tarea se editó correctamente', commentAdded: 'El comentario se agregó correctamente', projectAdded: 'El proyecto se creó correctamente', projectDeleted: 'El proyecto se eliminó correctamente', projectEdited: 'El proyecto se editó correctamente', memberExpelled: 'El miembro se expulsó correctamente', adminAdded: 'Se agregó el administrador correctamente', applicationSended: 'La solicitud fue enviada correctamente' }
